Ffprincipale:
    path:  /
    defaults: { _controller: "FiCoreBundle:Ffprincipale:index" }

Ffprincipale_new:
    path:  /new
    defaults: { _controller: "FiCoreBundle:Ffprincipale:new" }

Ffprincipale_create:
    path:  /create
    defaults: { _controller: "FiCoreBundle:Ffprincipale:create" }
    requirements: { methods: post }

Ffprincipale_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:Ffprincipale:edit" }

Ffprincipale_update:
    path:  /{id}/update
    defaults: { _controller: "FiCoreBundle:Ffprincipale:update" }
    requirements: { methods: post|put }

Ffprincipale_aggiorna:
    path:  /aggiorna
    defaults: { _controller: "FiCoreBundle:Ffprincipale:aggiorna" }
    requirements: { methods: post|put }

Ffprincipale_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:Ffprincipale:delete" }
    requirements: { methods: post|delete }

Ffprincipale_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiCoreBundle:Ffprincipale:delete" }
    requirements: { methods: post|delete }

Ffprincipale_griglia:
    path:  /griglia
    defaults: { _controller: "FiCoreBundle:Ffprincipale:Griglia" }
    requirements: { methods: get }

Ffprincipale_esportaexcel:
    path:  /esportaexcel
    defaults: { _controller: "FiCoreBundle:Ffprincipale:esportaexcel" }
    requirements: { methods: get|post }
