Operatori:
    path:  /
    defaults: { _controller: "FiCoreBundle:Operatori:index" }

Operatori_show:
    path:  /{id}/show
    defaults: { _controller: "FiCoreBundle:Operatori:show" }

Operatori_new:
    path:  /new
    defaults: { _controller: "FiCoreBundle:Operatori:new" }

Operatori_create:
    path:  /create
    defaults: { _controller: "FiCoreBundle:Operatori:create" }
    requirements: { methods: post }

Operatori_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:Operatori:edit" }

Operatori_update:
    path:  /{id}/update
    defaults: { _controller: "FiCoreBundle:Operatori:update" }
    requirements: { methods: post|put }

Operatori_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:Operatori:delete" }
    requirements: { methods: post|delete }

Operatori_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiCoreBundle:Operatori:delete" }
    requirements: { methods: post|delete }

Operatori_griglia:
    path:  /griglia
    defaults: { _controller: "FiCoreBundle:Operatori:Griglia" }
    requirements: { methods: get }