Fi\CoreBundle\Entity\allegati:
    type: entity
    #schema: fifree2
    table: allegati
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nometabella:
            type: string
            length: 255
            nullable: true
        indicetabella:
            type: integer
            nullable: true
        allegato:
            type: string
            length: 255
            nullable: true
        allegatofile:
            type: blob
            nullable: true
        datamodifica:
            type: datetime
            nullable: true