Fi\CoreBundle\Entity\Ffprincipale:
    type: entity
    table: Ffprincipale
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        descrizione:
            type: string
            length: 45
            nullable: true
    oneToMany:
        ffsecondarias:
            targetEntity: Ffsecondaria
            mappedBy: ffprincipale
            joinColumn:
                name: id
                referencedColumnName: ffprincipale_id