Fi\CoreBundle\Entity\Ffsecondaria:
    type: entity
    table: Ffsecondaria
    indexes:
        ffsecondaria_ffprincipale_fk_idx:
            columns: [ ffprincipale_id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        descsec:
            type: string
            length: 45
            nullable: true
        ffprincipale_id:
            type: integer
        data:
            type: date
            nullable: true
        intero:
            type: integer
            nullable: true
        importo:
            type: float
            precision: 10
            scale: 2
            nullable: true
        nota:
            type: string
            length: 4000
            nullable: true
        attivo:
            type: boolean
            nullable: true
    manyToOne:
        ffprincipale:
            targetEntity: Ffprincipale
            inversedBy: ffsecondarias
            joinColumn:
                name: ffprincipale_id
                referencedColumnName: id