Fi\CoreBundle\Entity\Operatori:
    type: entity
    table: Operatori
    indexes:
        fk_operatori_ruoli1_idx:
            columns: [ ruoli_id ]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        operatore:
            type: string
            length: 255
            nullable: true
        ruoli_id:
            type: integer
            nullable: true
    oneToMany:
        permessis:
            targetEntity: Permessi
            mappedBy: operatori
            joinColumn:
                name: id
                referencedColumnName: operatori_id
        storicomodifiches:
            targetEntity: Storicomodifiche
            mappedBy: operatori
            joinColumn:
                name: id
                referencedColumnName: operatori_id
        tabelles:
            targetEntity: Tabelle
            mappedBy: operatori
            joinColumn:
                name: id
                referencedColumnName: operatori_id
    manyToOne:
        ruoli:
            targetEntity: Ruoli
            inversedBy: operatoris
            joinColumn:
                name: ruoli_id
                referencedColumnName: id
                nullable: true