Fi\CoreBundle\Entity\Ruoli:
    type: entity
    table: Ruoli
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        ruolo:
            type: string
            length: 45
            nullable: true
        paginainiziale:
            type: string
            length: 255
            nullable: true
        is_superadmin:
            type: boolean
            nullable: true
        is_admin:
            type: boolean
            nullable: true
        is_user:
            type: boolean
            nullable: true
    oneToMany:
        operatoris:
            targetEntity: Operatori
            mappedBy: ruoli
            joinColumn:
                name: id
                referencedColumnName: ruoli_id
        permessis:
            targetEntity: Permessi
            mappedBy: ruoli
            joinColumn:
                name: id
                referencedColumnName: ruoli_id