parameters:
#    fi_core.example.class: Fi\CoreBundle\Example 
  ficorebundle.db.table_schema: 
  ficorebundle.db.table_prefix: __corebundle_
  
  fiQuery.class: Fi\OracleBundle\DependencyInjection\fiQuery
  oracle_GPS:
    utente: GPS
    password: GPS
    connessione: SIGRUDB
  oracle_P00:
    utente: P00
    password: F1PEZ0_1
    connessione: SIGRUDB
    #arguments: [%connessione%]
  oracle_adreader:
    utente: ADREADER
    password: LETTORE14
    connessione: SIGRUDB
    
services:
#    fi_core.example:
#        class: %fi_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    request:
        class:        Symfony\Component\HttpFoundation\Request

    fi.twig.fi_permessi_extension:
        class: Fi\CoreBundle\Twig\Extension\PermessiTwigExtension
        arguments: [ '@service_container', '@request' ]
        tags:
            - { name: twig.extension }
            
            
    fi.twig.fi_demo_extension:
      class: Fi\CoreBundle\Twig\Extension\DemoExtension
      tags:
        - { name: twig.extension }
      arguments: [ '@twig.loader' ]

    fi.twig.fi_utilita_extension:
      class: Fi\CoreBundle\Twig\Extension\UtilitaExtension
      tags:
        - { name: twig.extension }
      arguments: [ '@twig.loader' ]

    fi.twig.fi_misc_extension:
      class: Fi\CoreBundle\Twig\Extension\MiscExtension
      tags:
        - { name: twig.extension }
      arguments: [ '@service_container' ]

    fi.twig.demo.listener:
        class: Fi\CoreBundle\EventListener\ControllerListener
        arguments: ['@fi.twig.fi_demo_extension']
        tags:
            - { name: kernel.event_listener, event: kernel.controller,method: onKernelController }
    
    #Informazioni connessione database su Web Debug Toolbar
    data_collector.databaseinfo:
        class: Fi\CoreBundle\Collector\DatabaseInfoDataCollector
        arguments: [ '@service_container' ]
        tags:
            - { name: data_collector , template: "FiCoreBundle:Collector:databaseInfo", id: "databaseInfo" }
            
    ficorebundle.tblprefix_subscriber:
        class: Fi\CoreBundle\Subscriber\TablePrefixSubscriber
        arguments: [%ficorebundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
            
    ficorebundle.tblschema_subscriber:
        class: Fi\CoreBundle\Subscriber\TableSchemaSubscriber
        arguments: [%ficorebundle.db.table_schema%]
        tags:
            - { name: doctrine.event_subscriber }

    #    fi_oracle.example.class: Fi\OracleBundle\Example
    #    fi_jfestere.example.class: Fi\JfestereBundle\Example

    oracle_gps:
        class:     "%fiQuery.class%"
        #arguments: [@service_id, "plain_value", %parameter%]
        arguments: [%oracle_GPS%]
        
    oracle_sigru:
        class:     "%fiQuery.class%"
        #arguments: [@service_id, "plain_value", %parameter%]
        arguments: [%oracle_P00%]
        
    oracle_adreader:
        class:     "%fiQuery.class%"
        #arguments: [@service_id, "plain_value", %parameter%]
        arguments: [%oracle_adreader%]

            
