Tabelle:
    path:  /
    defaults: { _controller: "FiCoreBundle:Tabelle:index" }

Tabelle_configura:
    path:  /configura/{nometabella}
    defaults: { _controller: "FiCoreBundle:Tabelle:configura" }
    requirements: { methods: post|put|get }

Tabelle_stampatabella:
    path:  /stampatabella/{nometabella}
    defaults: { _controller: "FiCoreBundle:Tabelle:stampatabella" }
    requirements: { methods: post|put|get }
    
Tabelle_esportaexceltabella:
    path:  /esportaexcel/{nometabella}
    defaults: { _controller: "FiCoreBundle:Tabelle:esportaexcel" }
    requirements: { methods: post|put|get }
    
Tabelle_grigliapopup:
    path:  /{chiamante}/grigliapopup
    defaults: { _controller: "FiCoreBundle:Tabelle:grigliapopup" }
    requirements: { methods: post|put|get }

Tabelle_show:
    path:  /{id}/show
    defaults: { _controller: "FiCoreBundle:Tabelle:show" }

Tabelle_new:
    path:  /new
    defaults: { _controller: "FiCoreBundle:Tabelle:new" }

Tabelle_create:
    path:  /create
    defaults: { _controller: "FiCoreBundle:Tabelle:create" }
    requirements: { methods: post }

Tabelle_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:Tabelle:edit" }

Tabelle_aggiorna:
    path:  /aggiorna
    defaults: { _controller: "FiCoreBundle:Tabelle:aggiorna" }
    requirements: { methods: post|put }

Tabelle_update:
    path:  /{id}/update
    defaults: { _controller: "FiCoreBundle:Tabelle:update" }
    requirements: { methods: post|put }

Tabelle_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:Tabelle:delete" }
    requirements: { methods: post|delete }
    
Tabelle_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiCoreBundle:Tabelle:delete" }
    requirements: { methods: post|delete }

Tabelle_griglia:
    path:  /griglia
    defaults: { _controller: "FiCoreBundle:Tabelle:Griglia" }
    requirements: { methods: get }
    
Tabelle_listacampitabella:
    path:  /listacampitabella
    defaults: { _controller: "FiCoreBundle:Tabelle:listacampitabella" }
    requirements: { methods: get }
    
