language: php

php:
  - 5.6
  - 7.0
#  - hhvm

#sudo: required
#dist: trusty
cache:
  directories:
    - $HOME/.composer/cache
    
addons:
  firefox: "latest-esr"
  
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then phpenv config-add travis.php.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then phpenv config-add travis.php.ini; fi
  - echo -e '\nhhvm.libxml.ext_entity_whitelist = "file,http,https"' | sudo tee -a /etc/hhvm/php.ini
  - echo -e '\nhhvm.enable_zend_compat=true' | sudo tee -a /etc/hhvm/php.ini
  - echo 'date.timezone = "Europe/Rome"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'Europe/Rome' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - composer install
  - php app/console fifree2:install admin admin admin@admin.it --env=test
  - php app/console server:start --env=test
  - sh vendor/bin/selenium-server-standalone > /dev/null 2>&1 &
  - rm -rf app/cache/test
  - rm -rf app/cache/dev
  - chmod 777 -R app/cache app/logs 
  - chmod 777 src/ src/Fi app/AppKernel.php app/config/routing.yml
  - php app/console cache:clear --env=test
  - php app/console cache:warmup --env=test
  - php -i | grep timezone
  - php -i | grep ini

script:
  - ant

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/satooshi/php-coveralls/bin/coveralls -v; fi
  - vendor/bin/security-checker -n security:check
  - rm app/dbtest.sqlite
  - php app/console server:stop --env=test
  - pkill java

notifications:
  email:
  - andrea.manzi@comune.fi.it
