fi_core_Storicomodifiche:
    resource: "@FiCoreBundle/Resources/config/routing/storicomodifiche.yml"
    prefix:   /Storicomodifiche

FiCoreBundle_Ffprincipale:
    resource: "@FiCoreBundle/Resources/config/routing/ffprincipale.yml"
    prefix:   /Ffprincipale

FiCoreBundle_Ffsecondaria:
    resource: "@FiCoreBundle/Resources/config/routing/ffsecondaria.yml"
    prefix:   /Ffsecondaria    

FiCoreBundle_Funzioni:
    resource: "@FiCoreBundle/Resources/config/routing/funzioni.yml"
    prefix:   /funzioni
        
FiCoreBundle_ruoli:
    resource: "@FiCoreBundle/Resources/config/routing/ruoli.yml"
    prefix:   /Ruoli
        
FiCoreBundle_operatori:
    resource: "@FiCoreBundle/Resources/config/routing/operatori.yml"
    prefix:   /Operatori
    
FiCoreBundle_permessi:
    resource: "@FiCoreBundle/Resources/config/routing/permessi.yml"
    prefix:   /Permessi
    
FiCoreBundle_tabelle:
    resource: "@FiCoreBundle/Resources/config/routing/tabelle.yml"
    prefix:   /Tabelle

FiCoreBundle_opzioniTabella: 
  resource: "@FiCoreBundle/Resources/config/routing/opzionitabella.yml"
  prefix: /OpzioniTabella

FiCoreBundle_menuApplicazione: 
  resource: "@FiCoreBundle/Resources/config/routing/menuapplicazione.yml"
  prefix: /MenuApplicazione

# Expose security related features like login and logout
fos_user_security:
    prefix: /
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

FiCoreBundle_Storicomodifiche: 
  resource: "@FiCoreBundle/Resources/config/routing/storicomodifiche.yml"
  prefix: /Storicomodifiche
