parameters:
#    fi_core.example.class: Fi\CoreBundle\Example 
  ficorebundle.db.table_schema: 
  ficorebundle.db.table_prefix: __corebundle_
  
services:
#    fi_core.example:
#        class: %fi_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    request:
        class:        Symfony\Component\HttpFoundation\Request

    fi.twig.fi_permessi_extension:
        class: Fi\CoreBundle\Twig\Extension\PermessiTwigExtension
        arguments: [ '@service_container', '@request_stack' ]
        tags:
            - { name: twig.extension }
            
            
    fi.twig.fi_utilita_extension:
      class: Fi\CoreBundle\Twig\Extension\UtilitaExtension
      tags:
        - { name: twig.extension }
      arguments: [ '@twig.loader' ]

    fi.twig.fi_misc_extension:
      class: Fi\CoreBundle\Twig\Extension\MiscExtension
      tags:
        - { name: twig.extension }
      arguments: [ '@service_container' ]

    #Informazioni connessione database su Web Debug Toolbar
    data_collector.databaseinfo:
        class: Fi\CoreBundle\Collector\DatabaseInfoDataCollector
        arguments: [ '@service_container' ]
        tags:
            - { name: data_collector , template: "FiCoreBundle:Collector:databaseInfo", id: "databaseInfo" }
            
    ficorebundle.tblprefix_subscriber:
        class: Fi\CoreBundle\Subscriber\TablePrefixSubscriber
        arguments: [%ficorebundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
            
    ficorebundle.tblschema_subscriber:
        class: Fi\CoreBundle\Subscriber\TableSchemaSubscriber
        arguments: [%ficorebundle.db.table_schema%]
        tags:
            - { name: doctrine.event_subscriber }

    Storicomodifiche_repository: 
        class: Fi\CoreBundle\Entity\StoricomodificheRepository
        factory_service: 'doctrine.orm.default_entity_manager'
        factory_method:  'getRepository'
        arguments:  
            - 'Fi\CoreBundle\Entity\Storicomodifiche'

    Tabelle_repository: 
        class: Fi\CoreBundle\Entity\TabelleRepository
        factory_service: 'doctrine.orm.default_entity_manager'
        factory_method:  'getRepository'
        arguments:  
            - 'Fi\CoreBundle\Entity\Tabelle'        