fi_pannello_amministrazione:
    resource: "@FiPannelloAmministrazioneBundle/Resources/config/routing.yml"
    prefix:   /

fi_core:
    resource: "@FiCoreBundle/Resources/config/routing.yml"
    prefix:   /
