parameters:
#    fi_pannello_amministrazione.example.class: Fi\PannelloAmministrazioneBundle\Example

services:
#    fi_pannello_amministrazione.example:
#        class: %fi_pannello_amministrazione.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pannelloamministrazione.generateform:
        class: Fi\PannelloAmministrazioneBundle\DependencyInjection\GenerateForm
        arguments:
            ['@service_container']
            
    pannelloamministrazione.commands:
        class: Fi\PannelloAmministrazioneBundle\DependencyInjection\PannelloamministrazioneCommands
        arguments:
            ['@service_container']

    pannelloamministrazione.utils:
        class: Fi\PannelloAmministrazioneBundle\DependencyInjection\PannelloAmministrazioneUtils
        arguments:
            ['@service_container']

    pannelloamministrazione.command.generateentities:
        class: Fi\PannelloAmministrazioneBundle\Command\GenerateentitiesCommand
        public: false
        tags:
            -  { name: console.command }
            
    pannelloamministrazione.command.generateymlentities:
        class: Fi\PannelloAmministrazioneBundle\Command\GenerateymlentitiesCommand
        public: false
        tags:
            -  { name: console.command }
            
    pannelloamministrazione.command.checkgitversion:
        class: Fi\PannelloAmministrazioneBundle\Command\CheckgitversionCommand
        public: false
        tags:
            -  { name: console.command }            

    pannelloamministrazione.command.checksrc:
        class: Fi\PannelloAmministrazioneBundle\Command\ChecksrcCommand
        public: false
        tags:
            -  { name: console.command }
