fi_core_homepage:
    path:  /coredemo/
    defaults: { _controller: FiCoreBundle:Default:index }

FiCoreBundle_Ffprincipale:
    resource: "@FiCoreBundle/Resources/config/routing/ffprincipale.yml"
    prefix:   /Ffprincipale

FiCoreBundle_Ffsecondaria:
    resource: "@FiCoreBundle/Resources/config/routing/ffsecondaria.yml"
    prefix:   /Ffsecondaria    

FiCoreBundle_Funzioni:
    resource: "@FiCoreBundle/Resources/config/routing/funzioni.yml"
    prefix:   /funzioni
        
FiCoreBundle_ruoli:
    resource: "@FiCoreBundle/Resources/config/routing/ruoli.yml"
    prefix:   /Ruoli
        
FiCoreBundle_operatori:
    resource: "@FiCoreBundle/Resources/config/routing/operatori.yml"
    prefix:   /Operatori
    
FiCoreBundle_permessi:
    resource: "@FiCoreBundle/Resources/config/routing/permessi.yml"
    prefix:   /Permessi
    
FiCoreBundle_tabelle:
    resource: "@FiCoreBundle/Resources/config/routing/tabelle.yml"
    prefix:   /Tabelle

FiCoreBundle_allegati:
    resource: "@FiCoreBundle/Resources/config/routing/allegati.yml"
    prefix:   /Allegati


FiCoreBundle_opzioniTabella: 
  resource: "@FiCoreBundle/Resources/config/routing/opzionitabella.yml"
  prefix: /OpzioniTabella

FiCoreBundle_menuApplicazione: 
  resource: "@FiCoreBundle/Resources/config/routing/menuapplicazione.yml"
  prefix: /MenuApplicazione

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

