Fi\CoreBundle\Entity\Ffprincipale:
    properties:
        descrizione:
            - NotBlank: ~
            
Fi\CoreBundle\Entity\menuApplicazione:
    properties:
        nome:
            - NotBlank: ~