ffsecondaria:
    path:  /
    defaults: { _controller: "FiCoreBundle:ffsecondaria:index" }

ffsecondaria_new:
    path:  /new
    defaults: { _controller: "FiCoreBundle:ffsecondaria:new" }

ffsecondaria_create:
    path:  /create
    defaults: { _controller: "FiCoreBundle:ffsecondaria:create" }
    requirements: { methods: post }

ffsecondaria_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:ffsecondaria:edit" }

ffsecondaria_update:
    path:  /{id}/update
    defaults: { _controller: "FiCoreBundle:ffsecondaria:update" }
    requirements: { methods: post|put }

ffprincipale_aggiorna:
    path:  /aggiorna
    defaults: { _controller: "FiCoreBundle:ffsecondaria:aggiorna" }
    requirements: { methods: post|put }

ffsecondaria_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:ffsecondaria:delete" }
    requirements: { methods: post|delete }

ffsecondaria_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiCoreBundle:ffsecondaria:delete" }
    requirements: { methods: post|delete }

ffsecondaria_griglia:
    path:  /griglia
    defaults: { _controller: "FiCoreBundle:ffsecondaria:griglia" }
    requirements: { methods: get }
