menuApplicazione_container:
    path:  /
    defaults: { _controller: "FiCoreBundle:menuApplicazione:index" }

menuApplicazione_new:
    path:  /new
    defaults: { _controller: "FiCoreBundle:menuApplicazione:new" }

menuApplicazione_create:
    path:  /create
    defaults: { _controller: "FiCoreBundle:menuApplicazione:create" }
    requirements: { methods: post }

menuApplicazione_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:menuApplicazione:edit" }

menuApplicazione_update:
    path:  /{id}/update
    defaults: { _controller: "FiCoreBundle:menuApplicazione:update" }
    requirements: { methods: post|put }

menuApplicazione_aggiorna:
    path:  /aggiorna
    defaults: { _controller: "FiCoreBundle:menuApplicazione:aggiorna" }
    requirements: { methods: post|put }

menuApplicazione_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:menuApplicazione:delete" }
    requirements: { methods: post|delete }

menuApplicazione_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiCoreBundle:menuApplicazione:delete" }
    requirements: { methods: post|delete }

menuApplicazione_griglia:
    path:  /griglia
    defaults: { _controller: "FiCoreBundle:menuApplicazione:griglia" }
    requirements: { methods: get }
