opzioniTabella:
    path:  /
    defaults: { _controller: "FiCoreBundle:opzioniTabella:index" }

opzioniTabella_new:
    path:  /new
    defaults: { _controller: "FiCoreBundle:opzioniTabella:new" }

opzioniTabella_create:
    path:  /create
    defaults: { _controller: "FiCoreBundle:opzioniTabella:create" }
    requirements: { methods: post }

opzioniTabella_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:opzioniTabella:edit" }

opzioniTabella_update:
    path:  /{id}/update
    defaults: { _controller: "FiCoreBundle:opzioniTabella:update" }
    requirements: { methods: post|put }

opzioniTabella_aggiorna:
    path:  /aggiorna
    defaults: { _controller: "FiCoreBundle:opzioniTabella:aggiorna" }
    requirements: { methods: post|put }

opzioniTabella_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:opzioniTabella:delete" }
    requirements: { methods: post|delete }

opzioniTabella_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiCoreBundle:opzioniTabella:delete" }
    requirements: { methods: post|delete }

opzioniTabella_griglia:
    path:  /griglia
    defaults: { _controller: "FiCoreBundle:opzioniTabella:griglia" }
    requirements: { methods: get }
