permessi:
    path:  /
    defaults: { _controller: "FiCoreBundle:permessi:index" }

permessi_show:
    path:  /{id}/show
    defaults: { _controller: "FiCoreBundle:permessi:show" }

permessi_new:
    path:  /new
    defaults: { _controller: "FiCoreBundle:permessi:new" }

permessi_create:
    path:  /create
    defaults: { _controller: "FiCoreBundle:permessi:create" }
    requirements: { methods: post }

permessi_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:permessi:edit" }

permessi_update:
    path:  /{id}/update
    defaults: { _controller: "FiCoreBundle:permessi:update" }
    requirements: { methods: post|put }

permessi_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:permessi:delete" }
    requirements: { methods: post|delete }

permessi_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiCoreBundle:permessi:delete" }
    requirements: { methods: post|delete }

permessi_griglia:
    path:  /griglia
    defaults: { _controller: "FiCoreBundle:permessi:griglia" }
    requirements: { methods: get }