ruoli:
    path:  /
    defaults: { _controller: "FiCoreBundle:ruoli:index" }

ruoli_show:
    path:  /{id}/show
    defaults: { _controller: "FiCoreBundle:ruoli:show" }

ruoli_new:
    path:  /new
    defaults: { _controller: "FiCoreBundle:ruoli:new" }

ruoli_create:
    path:  /create
    defaults: { _controller: "FiCoreBundle:ruoli:create" }
    requirements: { methods: post }

ruoli_edit:
    path:  /{id}/edit
    defaults: { _controller: "FiCoreBundle:ruoli:edit" }

ruoli_update:
    path:  /{id}/update
    defaults: { _controller: "FiCoreBundle:ruoli:update" }
    requirements: { methods: post|put }

ruoli_delete:
    path:  /{id}/delete
    defaults: { _controller: "FiCoreBundle:ruoli:delete" }
    requirements: { methods: post|delete }
    
ruoli_deletemultiple:
    path:  /delete
    defaults: { _controller: "FiCoreBundle:ruoli:delete" }
    requirements: { methods: post|delete }

ruoli_griglia:
    path:  /griglia
    defaults: { _controller: "FiCoreBundle:ruoli:griglia" }
    requirements: { methods: get }