Fi\CoreBundle\Entity\Ffsecondaria:
    type: entity
    table: ffsecondaria
    indexes:
        ffsecondaria_ffprincipale_fk_idx:
            columns: [ffprincipale_id]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        descsec:
            type: string
            length: 45
            nullable: true
        ffprincipale_id:
            type: integer
    manyToOne:
        ffprincipale:
            targetEntity: Ffprincipale
            inversedBy: ffsecondarias
            joinColumn:
                name: ffprincipale_id
                referencedColumnName: id
                nullable: false